### ISSUE TITLE
Reference server error : POST http://localhost:2222/resources/update

### ISSUE THREAD

**Issue by ApuscasiteiSilviu** [sergiuiacob1/Timetable-Maker#15]
Nu se face update-ul cum trebuie pentru dependente.
Execut comanda:
{
	"id": 38,
	"type": "sala",
	"name": "BenQ",
	"capacity": 100,
	"dependencies": [39,40]
}

Si asta este de la Get resources:
![weqewqeqw](https://user-images.githubusercontent.com/22739599/40246152-5cd8119a-5ad0-11e8-8eec-92ebc007735c.png)

**Comment by MihaiBojescu** [comment]
Rezolvat în e089249a631d13751f0cecf3634478e019bfa60d
